# Generated by Django 2.1.7 on 2019-03-17 07:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agebu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegeo', models.CharField(max_length=13)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cve_loc', models.CharField(max_length=4)),
                ('cve_ageb', models.CharField(max_length=4)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegeo', models.CharField(max_length=2)),
                ('cve_ent', models.CharField(max_length=2)),
                ('nomgeo', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['nomgeo'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegeo', models.CharField(max_length=9)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cve_loc', models.CharField(max_length=4)),
                ('nomgeo', models.CharField(max_length=120)),
                ('ambito', models.CharField(max_length=6)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('entidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Entidad')),
            ],
            options={
                'ordering': ['nomgeo'],
            },
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegeo', models.CharField(max_length=16)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cve_loc', models.CharField(max_length=4)),
                ('cve_ageb', models.CharField(max_length=4)),
                ('cve_mza', models.CharField(max_length=3)),
                ('ambito', models.CharField(max_length=6)),
                ('tipomza', models.CharField(max_length=16)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('agebu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Agebu')),
                ('entidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Entidad')),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegeo', models.CharField(max_length=5)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('nomgeo', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('entidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Entidad')),
            ],
            options={
                'ordering': ['nomgeo'],
            },
        ),
        migrations.AddField(
            model_name='manzana',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Municipio'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Municipio'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Entidad'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Localidad'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Municipio'),
        ),
    ]
