# Generated by Django 2.1.7 on 2019-03-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanitaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agebr',
            name='P_15A17_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 15 a 17 años de edad.', null=True, verbose_name='Población femenina de 15 a 17 años'),
        ),
        migrations.AddField(
            model_name='agebr',
            name='P_8A14_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 8 a 14 años de edad.', null=True, verbose_name='Población femenina de 8 a 14 años'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='P_15A17_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 15 a 17 años de edad.', null=True, verbose_name='Población femenina de 15 a 17 años'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='P_8A14_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 8 a 14 años de edad.', null=True, verbose_name='Población femenina de 8 a 14 años'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='P_15A17_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 15 a 17 años de edad.', null=True, verbose_name='Población femenina de 15 a 17 años'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='P_8A14_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 8 a 14 años de edad.', null=True, verbose_name='Población femenina de 8 a 14 años'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='P_15A17_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 15 a 17 años de edad.', null=True, verbose_name='Población femenina de 15 a 17 años'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='P_8A14_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 8 a 14 años de edad.', null=True, verbose_name='Población femenina de 8 a 14 años'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='P_15A17_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 15 a 17 años de edad.', null=True, verbose_name='Población femenina de 15 a 17 años'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='P_8A14_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 8 a 14 años de edad.', null=True, verbose_name='Población femenina de 8 a 14 años'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='P_15A17_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 15 a 17 años de edad.', null=True, verbose_name='Población femenina de 15 a 17 años'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='P_8A14_F',
            field=models.PositiveIntegerField(blank=True, help_text='Mujeres de 8 a 14 años de edad.', null=True, verbose_name='Población femenina de 8 a 14 años'),
        ),
        migrations.AlterField(
            model_name='agebr',
            name='P_15A17_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 15 a 17 años de edad.', null=True, verbose_name='Población masculina de 15 a 17 años'),
        ),
        migrations.AlterField(
            model_name='agebr',
            name='P_8A14_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 8 a 14 años de edad.', null=True, verbose_name='Población masculina de 8 a 14 años'),
        ),
        migrations.AlterField(
            model_name='agebu',
            name='P_15A17_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 15 a 17 años de edad.', null=True, verbose_name='Población masculina de 15 a 17 años'),
        ),
        migrations.AlterField(
            model_name='agebu',
            name='P_8A14_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 8 a 14 años de edad.', null=True, verbose_name='Población masculina de 8 a 14 años'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='P_15A17_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 15 a 17 años de edad.', null=True, verbose_name='Población masculina de 15 a 17 años'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='P_8A14_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 8 a 14 años de edad.', null=True, verbose_name='Población masculina de 8 a 14 años'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='P_15A17_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 15 a 17 años de edad.', null=True, verbose_name='Población masculina de 15 a 17 años'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='P_8A14_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 8 a 14 años de edad.', null=True, verbose_name='Población masculina de 8 a 14 años'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nomgeo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='manzana',
            name='P_15A17_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 15 a 17 años de edad.', null=True, verbose_name='Población masculina de 15 a 17 años'),
        ),
        migrations.AlterField(
            model_name='manzana',
            name='P_8A14_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 8 a 14 años de edad.', null=True, verbose_name='Población masculina de 8 a 14 años'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='P_15A17_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 15 a 17 años de edad.', null=True, verbose_name='Población masculina de 15 a 17 años'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='P_8A14_M',
            field=models.PositiveIntegerField(blank=True, help_text='Hombres de 8 a 14 años de edad.', null=True, verbose_name='Población masculina de 8 a 14 años'),
        ),
    ]
