# Generated by Django 2.1.7 on 2019-03-17 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanitaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agebu',
            name='POBFEM',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='POBMAS',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='POBTOT',
            field=models.PositiveIntegerField(help_text='Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de personas en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad', null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Población total'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='P_0A2',
            field=models.PositiveIntegerField(null=True, verbose_name='Población de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='P_0A2_F',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='P_0A2_M',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='POBFEM',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='POBMAS',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='POBTOT',
            field=models.PositiveIntegerField(help_text='Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de personas en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad', null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Población total'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='P_0A2',
            field=models.PositiveIntegerField(null=True, verbose_name='Población de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='P_0A2_F',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='P_0A2_M',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='P_3YMAS',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(130)], verbose_name='Población de 3 años y más'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='POBFEM',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='POBMAS',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='POBTOT',
            field=models.PositiveIntegerField(help_text='Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de personas en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad', null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Población total'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='P_0A2',
            field=models.PositiveIntegerField(null=True, verbose_name='Población de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='P_0A2_F',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='P_0A2_M',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='POBFEM',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='POBMAS',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='POBTOT',
            field=models.PositiveIntegerField(help_text='Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de personas en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad', null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Población total'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='P_0A2',
            field=models.PositiveIntegerField(null=True, verbose_name='Población de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='P_0A2_F',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='P_0A2_M',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='POBFEM',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='POBMAS',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='POBTOT',
            field=models.PositiveIntegerField(help_text='Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de personas en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad', null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Población total'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='P_0A2',
            field=models.PositiveIntegerField(null=True, verbose_name='Población de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='P_0A2_F',
            field=models.PositiveIntegerField(null=True, verbose_name='Población femenina de 0 a 2 años'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='P_0A2_M',
            field=models.PositiveIntegerField(null=True, verbose_name='Población masculina de 0 a 2 años'),
        ),
    ]
