# Generated by Django 2.1.7 on 2019-03-17 10:37

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanitaria', '0002_auto_20190317_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agebr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegeo', models.CharField(max_length=9)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cve_ageb', models.CharField(max_length=4)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('POBTOT', models.PositiveIntegerField(help_text='Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de personas en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad', null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Población total')),
                ('POBMAS', models.PositiveIntegerField(null=True, verbose_name='Población masculina')),
                ('POBFEM', models.PositiveIntegerField(null=True, verbose_name='Población femenina')),
                ('P_0A2', models.PositiveIntegerField(null=True, verbose_name='Población de 0 a 2 años')),
                ('P_0A2_M', models.PositiveIntegerField(null=True, verbose_name='Población masculina de 0 a 2 años')),
                ('P_0A2_F', models.PositiveIntegerField(null=True, verbose_name='Población femenina de 0 a 2 años')),
                ('entidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Entidad')),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Localidad')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Municipio')),
            ],
        ),
    ]
