# Generated by Django 2.1.7 on 2019-03-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanitaria', '0003_agebr'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzana',
            name='agebr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humanitaria.Agebr'),
        ),
    ]
