# Generated by Django 2.1.7 on 2019-03-18 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanitaria', '0004_manzana_agebr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agebr',
            name='localidad',
        ),
        migrations.AddField(
            model_name='agebr',
            name='P_3YMAS',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(130)], verbose_name='Población de 3 años y más'),
        ),
        migrations.AddField(
            model_name='agebu',
            name='P_3YMAS',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(130)], verbose_name='Población de 3 años y más'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='P_3YMAS',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(130)], verbose_name='Población de 3 años y más'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='P_3YMAS',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(130)], verbose_name='Población de 3 años y más'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='P_3YMAS',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(130)], verbose_name='Población de 3 años y más'),
        ),
        migrations.AlterField(
            model_name='agebr',
            name='cvegeo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='agebu',
            name='cvegeo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='cvegeo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nomgeo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='manzana',
            name='cvegeo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='cvegeo',
            field=models.CharField(max_length=2),
        ),
    ]
